---
title: "Mock_fig"
author: "Ava Hamilton"
date: "2/1/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

library(readxl)

```


```{r}



mock_data_long = read_excel(path = "../MockData.xlsx") %>% janitor::clean_names() %>% 
  mutate(
    cbreak = as.factor(cbreak)
  )



rects <- data.frame(xstart = c(2014,2019), xend = c(2019,2022), col = letters[1:2])

ggplot()  + 
   scale_x_continuous(breaks = seq(2014,2022,2)) +
  geom_rect(data = rects, aes(xmin = xstart, xmax = xend, ymin = -Inf, ymax = Inf, fill = col), alpha = 0.5) +  
  scale_fill_manual(values = c("white", "#532565")) +
   geom_line(data = mock_data_long, aes(x = year, y = value, colour = type )) +
  geom_errorbar(data = mock_data_long, aes(x = year, ymin=value-sdl, ymax=value+sdh, colour = type), width=.2)+
   scale_color_manual(values=c('#999999','Black')) +
theme_minimal()  +
  theme(text = element_text(size = 16),
        axis.title.x = element_text(size=14, face="bold", colour = "black"),    
        axis.title.y = element_text(size=14, face="bold", colour = "black"),
        panel.grid = element_line(colour = "grey", linetype = "dotted"),
        panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank()
  ) +
  labs(x = "Year", y = "# Opioid Overdose Deaths", title = "Observed & simulated opioid overdose deaths in Erie County,
2014-2022", face = "bold")   + guides(fill = FALSE)


```




